<script>
	var Main = {
    	data() {
      		var validateFile = (rule, value, callback) => {
          		if(value.substring(value.length -3).toLowerCase() == "csv"){
					return true;
                }else{
                	callback(new Error('请上传CSV文件'));
                	return false;
                }
      		};
      		
      		return {ok  : false,
    	     	ruleForm: {
                    fileName: "",
                    date1:'',
                    date2:''
            		},
	            rules2: {
	            	fileName: [
	                    { required: true, message: "请上传文件", trigger: "change" },
	                    { validator: validateFile, trigger: "change" }
	                ],
	                date1: [
	                    { type: 'date', required: true, message: '请选择日期', trigger: 'change' }
	                  ],
	                  date2: [
	                    { type: 'date', required: true, message: '请选择时间', trigger: 'change' }
	                  ]
	           }
    		};
    	},
	    methods: {
	    	onFileChange: function() {
	            alert("onFileChange");
	        },
	        fileSelect: function() {
	        	const elem = this.$refs.fileUpload;
	        	elem.click();
	        },
	        onFileChange : function(files){
	        	if(files.target.files.length > 0){
	            	this.$data.ruleForm.fileName = files.target.files[0].name;
					this.$data.ok = true;
	            }
	        },
	        fileDel : function() {
	        	this.$refs.fileUpload.files = null;
	        	this.$data.ruleForm.fileName = "";
	        	this.$data.ok = false;
	        },
	        formSubmit : function(){
				alert(1);
	        },
	        submitForm(formName) {
	            this.$refs[formName].validate((valid) => {
	              if (valid) {
	                alert('submit!');
	              } else {
	                console.log('error submit!!');
	                return false;
	              }
	            });
			}
	    }
  	};
  	
	var Ctor = Vue.extend(Main)
	new Ctor().$mount('#app')
</script>