	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0">
    <title><?php echo $this->escape($this->title); ?></title>
    
    <link href="<?php echo $this->baseUrl() ?>/common/css/elementUI.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/css/common.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/paper/share/edit.css" media="screen" rel="stylesheet" type="text/css" >