	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=8" />
	<meta http-equiv="Pragma" content="no-cache">
	<meta http-equiv="Cache-Control" content="no-cache">
    <title><?php echo $this->escape($this->title); ?></title>
    
    <link href="<?php echo $this->baseUrl() ?>/common/jqwidgets/styles/jqx.base.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/jqwidgets/styles/jqx.dark.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/jqwidgets/styles/jqx.metro.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/css/standard.css" media="screen" rel="stylesheet" type="text/css" >