<div style="padding-left:10px;padding-right:10px;">
	<el-row :gutter="10">
		<el-col :span="5"><div class="grid-content"></div></el-col>
		<el-col :span="14">
		  	<div class="grid-content">
				<el-form :model="ruleForm" :rules="rules2" ref="ruleForm" label-width="100px" enctype="multipart/form-data">
					<div class="hero-unit" style="margin-top:10px;">
						<p class="text-center"><strong>CPカフェオーダー取り込み</strong></p>
					</div>
				
					<el-form-item prop="fileName" label-width="5px;">
				        <el-col :span="24">
					  		<el-input type="text" :readonly="true" style="width:80%;float:left;" ref="fileNm" v-model="ruleForm.fileName"></el-input>
							<el-button type="danger" v-show="ok" icon="el-icon-delete" style="float:left;" @click="fileDel">削除</el-button>
					  		<el-button type="info"   style="margin-left:10px;" @click="fileSelect" >选取文件</el-button>
							
					    	<input type="file" ref="fileUpload" @change="onFileChange" style="display: none;">
					  	</el-col>
				    </el-form-item>
			    
		  			<el-form-item required  label-width="5px;">
		    			<el-col :span="4">
		      				<el-form-item prop="date1">
		        				<el-date-picker type="year" placeholder="选择年" v-model="ruleForm.date1" style="width:150px;"></el-date-picker>
		        				<label>年</label>
		      				</el-form-item>
		    			</el-col>
		    			<el-col :span="4">
		      				<el-form-item prop="date2">
		        				<el-date-picker type="month" placeholder="选择月" v-model="ruleForm.date2" format="MM"  style="width:150px;"></el-date-picker>
		        				<label>月</label>
		      				</el-form-item>
		      			</el-col>
		      			<el-col :span="16"></el-col>
					</el-form-item>
					
					<el-form-item  label-width="5px;">
						<el-col :span="24">
							<el-button type="info" @click="submitForm('ruleForm')">CSV一括登録</el-button>
						</el-col>
					</el-form-item>
					
					<el-form-item  label-width="5px;">
						<el-col :span="24">
							<hr>
							<el-button type="info">経費コード別実績照会</el-button>
						</el-col>
					</el-form-item>
				</el-form>
	  		</div>
		</el-col>
		<el-col :span="5"><div class="grid-content"></div></el-col>
	</el-row>
</div>