	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=8" />
	<meta http-equiv="Pragma" content="no-cache">
	<meta http-equiv="Cache-Control" content="no-cache">
    <title><?php echo $this->escape($this->title); ?></title>
    
    <link href="<?php echo $this->baseUrl() ?>/common/jqwidgets/styles/jqx.base.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/jqwidgets/styles/jqx.light.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/jqwidgets/styles/jqx.dark.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/css/standard.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl() ?>/common/css/detailStandard.css" media="screen" rel="stylesheet" type="text/css" >
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/common/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/common/jqwidgets/jqxcore.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/common/jqwidgets/jqxmenu.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/common/jqwidgets/jqxloader.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/common/js/appTojqwidgetsImpl.js"></script>