<div id="jqxLoader"></div>
<div id="dialogContent"></div>

<input type="hidden" id="path_into" value="<?php echo $this->baseUrl().$_SERVER['PATH_INFO']?>"/>

<script type="text/javascript">
	<?php echo $this->render('js' . $_SERVER['PATH_INFO'] . '.phtml');?>
</script>

<link href="<?php echo $this->baseUrl() ?>/project/<?php echo str_replace("/", "", $_SERVER['PATH_INFO']) ?>/<?php echo str_replace("/", "", $_SERVER['PATH_INFO']) ?>.css" media="screen" rel="stylesheet" type="text/css" >