<el-row>
  	<el-col :span="6" style="padding-right:5px;">
  		<div class="grid-content">
  			<canvas id="myCanvas"  style="height:710px; width:100%;">your browser does not support the canvas tag </canvas>
  			<img id="mona" style="display:none;" src="./img/lapp.gif" height="710">
  		</div>
	</el-col>
	<el-col :span="18">
		<span style="color: #FF4949;">说明: </span>
  		<el-card class="box-card">
			<span style="color: #20A0FF;">{{ textarea }}</span>
		</el-card>
  	</el-col>
</el-row>