<div id='jqxMenu' style="display:none;">
	<ul>
		<li style='width: 50px;'>File
			<ul style='width: 250px;'>
				<li><a id="Save">Save</a></li>
				<li><a id="Close">Close</a></li>
			</ul>
		</li>
		<li style='width: 50px;'>Test
			<ul>
				<li><a id="Save1">PC products</a></li>
				<li><a id="Save2">Mobile products</a></li>
				<li><a id="Save3">All products</a></li>
			</ul>
		</li>
	</ul>
</div>